apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: __APP_NAME__
  namespace: __NAMESPACE__
spec:
  project: default
  source:
    repoURL: __REPO_URL__
    targetRevision: __TARGET_REVISION__
    path: __PATH__
    helm:
      valueFiles:
        - values.yaml
        - overrides.yml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: __NAMESPACE__
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
